function fRanges = get_franges(expData, header)
%[fRanges] = get_franges(expData; 'header')
% function gets the frequencies from either the expData or the header, if
% that fails
%
% Parameters
% ----------
%   expData: struct
%       structure generated by load(run_000*.mat)
%   header: struct
%       struct acquired by load_header(run_000*_header.txt)

arguments
    expData
    header = 'none'
end

try
    f1 = expData.freqList(1:size(expData.disp1,2));
    f2 = expData.freqList(size(expData.disp1,2)+1:end);
catch
    f1 = linspace(header.startfreq1_Hz,header.endfreq1_Hz, header.numfreqs);
    f2 = linspace(header.startfreq2_Hz,header.endfreq2_Hz, header.numfreqs);
end

f1 = f1/1E9;
f2 = f2/1E9;
fRanges = {f1, f2};
end